admin/config/routes.rb
Rails.application.routes.draw do
  resources :clients do
    resources :subscriptions, shallow: true
  end
end

admin/app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord
  include ActiveModel::Model
  include ActiveModel::Attributes

  attribute :created_at, :datetime
  attribute :updated_at, :datetime

  def to_param
    id&.to_s
  end
end

admin/app/models/client.rb
# frozen_string_literal: true

class Client < ApplicationRecord
  attribute :id, :integer
  attribute :name, :string
  attribute :cpf, :string
  attribute :email, :string
end

admin/app/models/subscription.rb
# frozen_string_literal: true

class Subscription < ApplicationRecord
  attribute :id, :integer
  attribute :client_id, :integer
  attribute :phone_model, :string
  attribute :imei, :string
  attribute :full_price, :decimal
  attribute :payments, :integer
end

admin/app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :create_service
  after_action :close_service

  protected

  def create_service
    @service = SubSub.build
  end

  def close_service
    @service&.close
  end
end

admin/app/controllers/clients_controller.rb
# frozen_string_literal: true

class ClientsController < ApplicationController
  before_action :set_client, only: %i[show edit update destroy]

  # GET /clients
  def index
    *, @clients = @service.all_clients
  end

  # GET /clients/1
  def show; end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit; end

  # POST /clients
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      ok, result = @service.create_client(client_params)

      if ok
        format.html { redirect_to result, notice: 'Client was successfully created.' }
      else
        result.populate_model(@client)
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /clients/1
  def update
    respond_to do |format|
      ok, result = @service.update_client(params[:id], client_params)

      if
        format.html { redirect_to result, notice: 'Client was successfully updated.' }
      else
        @client = Client.new(client_params)
        result.populate_model(@client)

        format.html { render :edit }
      end
    end
  end

  # DELETE /clients/1
  def destroy
    @service.delete_client(params[:id])

    respond_to do |format|
      format.html { redirect_to clients_url, notice: 'Client was successfully destroyed.' }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_client
    *, @client = @service.get_client(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def client_params
    params.require(:client).permit(:name, :cpf, :email)
  end
end

admin/app/controllers/subscriptions_controller.rb
# frozen_string_literal: true

class SubscriptionsController < ApplicationController
  before_action :set_client_id, only: %i[index new create]
  before_action :set_subscription, only: %i[show edit update destroy]

  # GET /clients/1/subscriptions
  def index
    *, @subscriptions = @service.get_subscriptions(@client_id)
  end

  # GET /subscriptions/1
  def show; end

  # GET /clients/1/subscriptions/new
  def new
    @subscription = Subscription.new
  end

  # GET /subscriptions/1/edit
  def edit; end

  # POST /subscriptions
  def create
    @subscription = Subscription.new(subscription_params)

    respond_to do |format|
      ok, result = @service.create_subscription(@client_id, subscription_params)

      if ok
        format.html { redirect_to subscription_path(result), notice: 'Subscription was successfully created.' }
      else
        result.populate_model(@subscription)
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /subscriptions/1
  def update
    respond_to do |format|
      ok, result = @service.update_subscription(params[:id], subscription_params)

      if ok
        format.html { redirect_to subscription_path(@subscription), notice: 'Subscription was successfully updated.' }
      else
        @subscription = Subscription.new(subscription_params.merge(
                                           'client_id' => @subscription.client_id, 'id' => params[:id]
                                         ))
        result.populate_model(@subscription)

        format.html { render :edit }
      end
    end
  end

  # DELETE /subscriptions/1
  def destroy
    @service.delete_subscription(params[:id])

    respond_to do |format|
      format.html { redirect_to client_subscriptions_url(@subscription.client_id), notice: 'Subscription was successfully destroyed.' }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_subscription
    *, @subscription = @service.get_subscription(params[:id])
  end

  def set_client_id
    @client_id = params[:client_id]
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def subscription_params
    params.require(:subscription).permit(:phone_model, :imei, :full_price, :payments)
  end
end

admin/app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

admin/app/helpers/clients_helper.rb
# frozen_string_literal: true

module ClientsHelper
end

admin/app/helpers/subscriptions_helper.rb
# frozen_string_literal: true

module SubscriptionsHelper
end

admin/app/views/clients/_form.html.erb
<%= form_with(model: client, url: url, method: method, local: true) do |form| %>
  <% if client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
      <% client.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :cpf %>
    <%= form.text_field :cpf %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

admin/app/views/clients/edit.html.erb
<h1>Editing Client</h1>

<%= render 'form', client: @client, url: client_path(@client), method: :put %>

<%= link_to 'Show', client_path(@client) %> |
<%= link_to 'Back', clients_path %>

admin/app/views/clients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Clients</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Cpf</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clients.each do |client| %>
      <tr>
        <td><%= client.name %></td>
        <td><%= client.cpf %></td>
        <td><%= client.email %></td>
        <td><%= link_to 'Subscriptions', client_subscriptions_path(client) %></td>
        <td><%= link_to 'Show', client_path(client) %></td>
        <td><%= link_to 'Edit', edit_client_path(client) %></td>
        <td><%= link_to 'Destroy', client_path(client), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Client', new_client_path %>

admin/app/views/clients/new.html.erb
<h1>New Client</h1>

<%= render 'form', client: @client, url: clients_path, method: :post %>

<%= link_to 'Back', clients_path %>

admin/app/views/clients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @client.name %>
</p>

<p>
  <strong>Cpf:</strong>
  <%= @client.cpf %>
</p>

<p>
  <strong>Email:</strong>
  <%= @client.email %>
</p>

<%= link_to 'Edit', edit_client_path(@client) %> |
<%= link_to 'Back', clients_path %>

admin/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SubSubAdmin</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

admin/app/views/subscriptions/_form.html.erb
<%= form_with(model: subscription, url: url, method: method, local: true) do |form| %>
  <% if subscription.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(subscription.errors.count, "error") %> prohibited this subscription from being saved:</h2>

      <ul>
      <% subscription.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :phone_model %>
    <%= form.text_field :phone_model %>
  </div>

  <div class="field">
    <%= form.label :imei %>
    <%= form.text_field :imei %>
  </div>

  <div class="field">
    <%= form.label :full_price %>
    <%= form.text_field :full_price %>
  </div>

  <div class="field">
    <%= form.label :payments %>
    <%= form.number_field :payments %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

admin/app/views/subscriptions/edit.html.erb
<h1>Editing Subscription</h1>

<%= render 'form', subscription: @subscription, url: subscription_path(@subscription), method: :put %>

<%= link_to 'Show', subscription_path(@subscription) %>
<%= link_to 'Back', client_subscriptions_path(@subscription.client_id) %>

admin/app/views/subscriptions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Subscriptions for</h1>

<table>
  <thead>
    <tr>
      <th>Phone model</th>
      <th>Imei</th>
      <th>Full price</th>
      <th>Payments</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @subscriptions.each do |subscription| %>
      <tr>
        <td><%= subscription.phone_model %></td>
        <td><%= subscription.imei %></td>
        <td><%= subscription.full_price %></td>
        <td><%= subscription.payments %></td>
        <td><%= link_to 'Show', subscription_path(subscription) %></td>
        <td><%= link_to 'Edit', edit_subscription_path(subscription) %></td>
        <td><%= link_to 'Destroy', subscription_path(subscription), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Subscription', new_client_subscription_path(@client_id) %>
<%= link_to 'Back', client_path(@client_id) %>

admin/app/views/subscriptions/new.html.erb
<h1>New Subscription</h1>

<%= render 'form', subscription: @subscription, url: client_subscriptions_path(@client_id), method: :post %>

<%= link_to 'Back', client_subscriptions_path(@client_id) %>

admin/app/views/subscriptions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Phone model:</strong>
  <%= @subscription.phone_model %>
</p>

<p>
  <strong>Imei:</strong>
  <%= @subscription.imei %>
</p>

<p>
  <strong>Full price:</strong>
  <%= @subscription.full_price %>
</p>

<p>
  <strong>Payments:</strong>
  <%= @subscription.payments %>
</p>

<%= link_to 'Edit', edit_subscription_path(@subscription) %> |
<%= link_to 'Back', client_subscriptions_path(@subscription.client_id) %>